version: "3.7"

services:
  # binary:
  #   image: metacall/builder_binary
  #   container_name: metacall_builder_binary
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: builder_binary
  #   entrypoint: /builder

  # rootless:
  #   image: metacall/builder_rootless
  #   container_name: metacall_builder_rootless
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: builder_rootless
  #   entrypoint: /home/user/builder.sh
  #   security_opt:
  #     - "seccomp=unconfined"
  #     - "apparmor=unconfined"
  #   network_mode: "host"

  client:
    image: metacall/builder_client
    container_name: metacall_builder_client
    build:
      context: .
      dockerfile: Dockerfile
      target: builder_client
    entrypoint: /home/builder.sh
    network_mode: "host"
    depends_on:
      - buildkit

  buildkit:
    image: moby/buildkit
    container_name: metacall_builder_buildkit
    privileged: true
    network_mode: "host"
    healthcheck:
      test: buildctl debug workers
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 1s

# docker run -it --rm --privileged --entrypoint buildctl-daemonless.sh moby/buildkit:master build

# docker run \
#     -it \
#     --rm \
#     --privileged \
#     -v /path/to/dir:/tmp/work \
#     --entrypoint buildctl-daemonless.sh \
#     moby/buildkit:master \
#         build \
#         --frontend dockerfile.v0 \
#         --local context=/tmp/work \
#         --local dockerfile=/tmp/work