version: "3.7"

# volumes:
#   buildkit:

services:
  binary:
    image: metacall/builder_binary
    container_name: metacall_builder_binary
    build:
      context: .
      dockerfile: Dockerfile
      target: builder_binary
    entrypoint: /builder ${BUILDER_ARGS:-}

  rootless:
    image: metacall/builder_rootless
    container_name: metacall_builder_rootless
    build:
      context: .
      dockerfile: Dockerfile
      target: builder_rootless
    entrypoint: /home/user/builder.sh ${BUILDER_ARGS:-}
    security_opt:
      - "seccomp=unconfined"
      - "apparmor=unconfined"
    network_mode: "host"

  client:
    image: metacall/builder_client
    container_name: metacall_builder_client
    build:
      context: .
      dockerfile: Dockerfile
      target: builder_client
    entrypoint: /home/builder.sh ${BUILDER_ARGS:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - buildkit:/run/user/1000/buildkit/buildkitd.sock
    depends_on:
      - buildkit

  buildkit:
    image: moby/buildkit
    container_name: metacall_builder_buildkit
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock
      - buildkit:/run/buildkit/buildkitd.sock
    healthcheck:
      test: buildctl debug workers
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 1s
