name: Build and Test MetaCall Builder for Startup

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Startup
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: docker compose build

      - name: Test Binary
        env:
          BUILDER_ARGS: "runtime rb"
        run: docker compose up --exit-code-from binary binary

      - name: Docker System Prune
        run: docker system prune -af

      - name: Test Startup Rootless
        run: ./test/test.sh rootless startup

      - name: Docker System Prune
        run: docker system prune -af

      - name: Test Startup Daemon
        run: ./test/test.sh client startup
